# adjusted from: https://gideonwolfe.com/posts/sysadmin/tig/intro/
# changed path's and removed traefik

version: '2'
services:
#    ________________   _____ __             __
#   /_  __/  _/ ____/  / ___// /_____ ______/ /__
#    / /  / // / __    \__ \/ __/ __ `/ ___/ //_/
#   / / _/ // /_/ /   ___/ / /_/ /_/ / /__/ ,<
#  /_/ /___/\____/   /____/\__/\__,_/\___/_/|_|
#
   grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
         - 3000:3000
      volumes:
         - /srv/dev-disk-by-label-MyPassport/appdata/grafana/data:/var/lib/grafana
      restart: always
      user: "0"
      environment:
         - "GF_SERVER_ROOT_URL=your.grafana.url"

   influxdb_V1:
      image: influxdb
      container_name: influxdb
      restart: always
      ports:
         - 8086:8086
      volumes:
         - /srv/dev-disk-by-label-MyPassport/appdata/influxdb/:/var/lib/influxdb


   telegraf:
      image: telegraf
      hostname: omv
      volumes:
         - "/:/hostfs:ro"
         - "/etc:/hostfs/etc:ro"
         - "/proc:/hostfs/proc:ro"
         - "/sys:/hostfs/sys:ro"
         - "/var:/hostfs/var:ro"
         - "/run:/hostfs/run:ro"
         - "/srv/dev-disk-by-label-MyPassport/appdata/telegraf.conf:/etc/telegraf/telegraf.conf"
         - "/var/run/docker.sock:/var/run/docker.sock:ro"
      environment:
         - "HOST_ETC=/hostfs/etc"
         - "HOST_PROC=/hostfs/proc"
         - "HOST_SYS=/hostfs/sys"
         - "HOST_VAR=/hostfs/var"
         - "HOST_RUN=/hostfs/run"
         - "HOST_MOUNT_PREFIX=/hostfs"
      ports:
         - 8888:8888


