# adjusted from: https://medium.com/@musaib_khan/setup-telegraf-influxdb-and-grafana-in-docker-b1c6ac6bd523
# set PWD as env variable in stack when deploying this with portainer
# Move  telegraf.conf tp cprrect place
version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
    - 3000:3000
    networks:
    - monitoring
    volumes:
    - $PWD/tig/grafana:/vol01/Docker/monitoring
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
    - 8086:8086
    networks:
     - monitoring
    volumes:
    - $PWD/tig/influxdb:/vol01/Docker/monitoring
    environment:
    - INFLUXDB_DB=telegraf
    - INFLUXDB_USER=telegraf
    - INFLUXDB_ADMIN_ENABLED=true
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=Welcome123
  telegraf:
     image: telegraf
     container_name: telegraf
     restart: always
     extra_hosts:
     - "influxdb:192.168.1.111"
     environment:
       HOST_PROC: /rootfs/proc
       HOST_SYS: /rootfs/sys
       HOST_ETC: /rootfs/etc
     volumes:
     - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /sys:/rootfs/sys:ro
     - /proc:/rootfs/proc:ro
     - /etc:/rootfs/etc:ro
